global  vid ;
vid = videoinput('winvideo', 2, 'RGB24_1280x960');
src = getselectedsource(vid);
src.Gain = 39;
src.Exposure = -6;
src.Brightness = 128;
src.Contrast = 40;
src.Saturation = 140;
src.Sharpness = 24;
src.WhiteBalance = 4000;
vid.ReturnedColorspace = 'rgb';
%preview(vid);
pause(2);
% img = getsnapshot(vid);
% [arena, rect] = imcrop(img);
% vid.ROIPosition = rect;
vid.ROIPosition = [240 4 907 905];
pause(2);
%start(vid);
arena = getsnapshot(vid);
img = arena;
% 'opened'
%img = imread('img.jpg');
arena = imresize(img, [481 481]);
global connect;
 %connect =  serial('COM8','BaudRate',9600);
 %fopen(connect);
 pause(2);
global red;
global green;
global black;
global white;
global rgb1;
global rgb2;

%global indix;
%global indiy;
global a;
red = sampleval(arena);
green = sampleval(arena);
black = sampleval(arena);
rgb1 = sampleval(arena);
rgb2 = sampleval(arena);
white = sampleval(arena);
work(connect,vid);
fclose(connect);
